### ISSUE TITLE
How to Set Up Data Series 

### ISSUE THREAD

**Issue by homman** [shutterstock/rickshaw#115]
Hi evryone
I would like to use the graphic-interactive (that of example examples / extensions.html) and I wanted to enter custom values.
How do I insert custom values​​?

I tried to understand the Rickshaw.Fixtures.RandomData js files, which are created from the values ​​that you see in the example, but I could not understand how the values ​​are to tap.

How do I represent dates on the x-axis?
What kind of dates (SimpleDate, ...) should I use?
How do I set the values ​​for the y-axis?

If anyone can give me an example of the insertion of
individual values ​​([x, y]) would understand perfectly.
In practice I have to change this part:

// set up our data series with 50 random data points

var seriesData = [ [], [], [], [], [], [], [], [], [] ];
var random = new Rickshaw.Fixtures.RandomData(150);

for (var i = 0; i < 150; i++) {
    random.addData(seriesData);
}
This can be some value :

[0.12, '30/Aug/2012 11:27:05]
[1.21, '30/Aug/2012 11:27:14']
[2.10, '30/Aug/2012 15:50:44']
[3.32, '30/Aug/2012 15:51:09']

How i can put them in the chart?

I'm supposed to take the values ​​from a db and represent them on a chart.
I can take the values ​​but do not know how to pass to the function that draws the graph.

Thanks in advance

**Comment by siddmegadeth** [comment]
How can we implemne t timestamp on x axis for rickshaw
i am using angular-rickshaw


 $scope.cpuOptions = 
                 {
                    renderer: "line"
                 };
                 $scope.cpuSeries = series;
                 $scope.cpuFeatures = 
                 {
                   palette : "colorwheel",
                    hover: 
                    {
                        xFormatter: function(x) 
                        {
                           return new Date(x * 1000);
                        },
                        yFormatter: function(y) 
                        {
                            return   Math.round(y)+" Percent";
                        }
                    },
                     xAxis: {
                        timeUnit: '15 minute'
                    },
                    yAxis: 
                    {
                        tickFormat: 'formatKMBT'
                    },
                     legend: 
                     {
                        toggle: true,
                        highlight: true
                    }
                  };



How can i convert X axis to 15 minutes please help

**Comment by ZodaBit** [comment]
I have x values stored in an array lets say xval=[2,3,4,5] and yval=[1234,1256,16734,1234] how can i display this on the rick show graph i tried 
for(var i=0;i<4;i++)
{
  var data=[{x: xval[i],y:yval[i]}]
}
not working this way !! any help woud be appreciate
