### ISSUE TITLE
Support for null values in line/area graphs

### ISSUE THREAD

**Issue by fdietz** [shutterstock/rickshaw#121]
Since rickshaw can't handle null values, I usually tend to fill it up with integer 0 values. But, this leads to bad results if there's a lot of data missing - a sawtooth pattern. I'd prefer to actually skip drawing of null values. 

Am i wrong here or missing something? I've followed some more leads in d3.js and found a ticket describing the same problem.

A similiar discussion of this problem in d3.js:
https://github.com/mbostock/d3/issues/583

And a pull request from 6 months ago:
https://github.com/mbostock/d3/pull/594

It is possible to use this in rickshaw.js to achieve a similar result?

Kind regards,
-Frederik

**Comment by jktaylor21** [comment]
Solution with the current version is fairly simple - just fill your series will nulls for the missing points. The fill function works pretty well for this:

    Rickshaw.Series.fill(series, null);

Seems to work well for area, line, bar and scatter.
