### ISSUE TITLE
Huge memory leaks in Rickshaw

### ISSUE THREAD

**Issue by mkalinkin** [shutterstock/rickshaw#166]
Hello,

We are developing a data analytics application with web visualization. We need to visualize many html charts in real time (e.g.,  several dashboard with 10-20 line charts having 300 points and updated 5 times per second).

We found that our needs are more  or less good served by d3 rickshaw library. Among many other javascript libraries, it seems having best (or nearly best) performance

However, we also detected big memory leaks. Below are the details.

Our code is here: http://depositfiles.com/files/igs2z1o36

rickshaw-master\examples\test_update.html - plotting generated data in real time. Sliding window is organized manually. Memory leak for currently used parameters is ~ 8 Mb/sec.
rickshaw-master\examples\test_update_series.html - plotting generated data in real-time. Sliding window is organized via Rickshaw Series addon. Same memory leak.

In test_update.html, charts are updated using following lines of code:

 function updateChart() {  
  for(var g = 0; g < charts; g++){
   yValues[g] += rnd(); data[g].shift(); data[g].push({x: xValue, y: yValues[g]});
  }
  xValue += 1;
  graph.update();
  // console.log(yValues)
 }  
 setInterval(updateChart, interval);

While debugging, we have revealed function render (Rickshaw.Graph.Renderer.js:75), where current svg:path (one for each chart) is deleted и and new path with new data is added.  If comment that part of code, memory leaks disappear.

In Crome webdevtools dump we found that there are a lot of remaining elements "SVGPathElement" (their amount increase linearly with time). Most part of them seems to be outside DOM (we tried to delete elements by remove() function, but it seems that still somewhere remain links to these elements. Besides of grow of SVGPathElement amount, we observed grow of amount of some arrays (with similar dimension as SVGPathElement ). This might lead to the conclusion, that somewhere links to the arrays with previous data are stored causing memory leaks.

However, despite this considerations, we failed to locate exact reason of the memory leaks and find a solution to this problem.

Best regards,
Mikhail Kalinkin.

**Comment by leeoniya** [comment]
https://github.com/leeoniya/uPlot
