### ISSUE TITLE
Annotations Don't Appear Until User Rolls Over Legend

### ISSUE THREAD

**Issue by rgilman** [shutterstock/rickshaw#366]
The title says it. This issue is also discussed at [stackoverflow](http://stackoverflow.com/questions/19662180/rickshaw-annotations-dont-appear-until-user-rolls-over-legend). The issue also shows up in http://code.shutterstock.com/rickshaw/examples/extensions.html but you have to be quick to demonstrate it before the built-in update.

The fix I'm using is:

```
    setTimeout(function(){
        graph.update();
    },500);

```

in my drawChart function. This gets the annotations to appear soon enough without extra cpu load. But this is just a workaround -- it needs a real fix.

**Comment by veerulion** [comment]
Is there any click event handlers in Rickshaw?if there can you please provide an example on it.
