### ISSUE TITLE
Add custom events and annotations to graphs

### ISSUE THREAD

**Issue by jorgeas80** [shutterstock/rickshaw#367]
I don't know if this is possible using Rickshaw: define custom events and annotations, and add them to graph. I mean something like this: http://www.flotcharts.org/flot/examples/annotating/index.html

What I'm looking for is the ability to define an event for a given value of X and/or Y. So, this event can be shown in the graph, like the example above.

Many thanks anyway

**Comment by Soundman32** [comment]
> Hi, you can add annotations by providing an x-axis value and a message as described here:
> http://code.shutterstock.com/rickshaw/#annotations
> 
> With annotations in place, you should be able to use CSS to achieve a presentation similar to what shows in your example. Good luck!

Link is now a 404

**Comment by jasonoh** [comment]
@Soundman32 hello, this is the updated location: https://tech.shutterstock.com/rickshaw/#annotations
