### ISSUE TITLE
Change width-height dynamically

### ISSUE THREAD

**Issue by Sly777** [shutterstock/rickshaw#369]
I'm using rickshaw on one of my projects. But i need to change width/height dynamically (you can think like responsive) How can i do that? I looked examples and codes but i didn't find any good solution.

**Comment by tsareg** [comment]
Gist is dead (. Can somebody re-post it?

**Comment by julian-boolean** [comment]
Sorry, changed my username. Here is the gist.
https://gist.github.com/julian-boolean/8339982

**Comment by tsareg** [comment]
@julian-boolean Thanks a lot!
