### ISSUE TITLE
Please consider linking to screencast

### ISSUE THREAD

**Issue by hendrikswan** [shutterstock/rickshaw#374]
Hi ya,

I've created a high quality tutorial screencast on using rickshaw in angularjs. 

It would be great if you could link to it on the readme or on http://code.shutterstock.com/rickshaw/ or both :) 

The screencast takes you through binding to some real data, adding axes, showing a customized tooltip, panning and zooming, etc. 
It also showcase the ease with which you can customize the components through CSS.

This is the url for the screencast: http://tagtree.tv/d3-with-rickshaw-and-angular

Would you please consider linking to it? 

Thanks

**Comment by cesine** [comment]
hi @hendrikswan a couple weeks back i was working on adding examples for frameworks like angular and i found your screencast, it's pretty awesome! i sent you a pr to fix a bug in the render https://github.com/hendrikswan/tagtree-rickshaw/pull/2 im hoping to wrap up the examples in a few weeks, probably building on what you built and including links to the screencast etc...
