### ISSUE TITLE
Bar chart inconsistency between browsers

### ISSUE THREAD

**Issue by edmundoa** [shutterstock/rickshaw#461]
Hello,

I am trying to create a bar chart containing data over a span of days using Rickshaw (v1.5.0). Some days may not have any data, so I'm adding a point at the beginning and end of that period of time to ensure the whole timespan is shown on the graph. This seems to be working fine on most browsers (Chrome, Safari and IE11), but on Firefox 30 and 31 the bars are overlapped and the x-axis is showing a wider time period. The attached image shows the bar chart I can see on Firefox, and the the code generating that chart is in this jsfiddle: http://jsfiddle.net/2AYwr/

Debugging Rickshaw a little, I have seen that the problem seems to be in the `_frequentInterval` function inside `Rickshaw.Graph.Renderer.Bar`, as it's returning different values on Chrome and Firefox, but I'm really not sure how to fix it. Could you please take a look into it?

Thank you in advance!

![firefox](https://cloud.githubusercontent.com/assets/716185/3723505/17f0ba72-1674-11e4-86ed-bbd177b21198.png)

**Comment by mostr** [comment]
Hey @edmundoa, I'm stuck with exactly the same issue. Have you found any workaround for that?

**Comment by edmundoa** [comment]
Hi @mostr,

In the end I extended the `Bar` renderer in order to accept a resolution field. I guess an easier solution is to go through your data and add an empty point in each *tick* with the resolution you want to achieve. 

Here's the code in case you are interested: https://gist.github.com/edmundoa/a5bad160026c0f2c230e
