### ISSUE TITLE
`object is not a function` error after uglify minification

### ISSUE THREAD

**Issue by jzaefferer** [shutterstock/rickshaw#52]
When minifying Rickshaw with uglify (via requirejs/r.js), I'm getting an "object is not a function" error somewhere from Rickshaw, while trying to render a bar graph. Here's a screenshot from Chrome's script panel, paused on uncaught exceptions: http://bassistance.de/i/50e880.png

So the error is thrown in `Rickshaw.Graph.Renderer.Bar.Rickshaw.Class.create.initialize`, which is reasonable, as both arguments are objects, not functions. Though I have no idea why an object is passed where a function is expected. Maybe someone more familar with the code base can tell.

Here's the code to render the graph in our application: https://gist.github.com/5552abdf24227e5f7cb6
Without minification that works fine.

**Comment by kermit666** [comment]
I can confirm that this is a pain point using the basic Yeoman web app template as well - the usemin step minimises the library as well and I really don't know how to add an exception there. Anyone maybe knows?

**Comment by willsu** [comment]
@jzaefferer Your suggestion worked for me.. Many more years later! Thanks a lot. I'm glad I found this issue before spending my entire day on this problem.

FWIW, I was not using rickshaw. I was using gulp-uglify 1.0.2 with prototypejs 1.7.2, but the fundamental issue still stands.

For historical purposes, I'd like to share some more technical details on why @jzaefferer 's fix solves the problem:

Prototype has an implicit dependency on arguments in the 0th position of a function call that are are named '$super' that have been created with the Class.create method. It is silly, IMHO, to have technical dependencies on an 'argument name' in any function in any language (let alone JavaScript). JS minifiers, like Uglifyjs, cannot reasonable detect this dependency when their algorithms are run against a static file. 

This is the offending bit of Prototype code (from the Class -> addMethods function):

```
if (ancestor && Object.isFunction(value) &&
          value.argumentNames()[0] == "$super") {
```

I don't know a JS minifier (in it's right mind) that would replace that "$super" String reference with the modified argument in a function caller (which also should not have to be standardized anyway..).. And really it shouldn't.

Thanks again to those who contributed to this thread!

**Comment by kermit666** [comment]
Tried different exclude options, but none of them worked. In the end I had to disable usemin's minification  for JavaScript like this:

```
        useminPrepare: {
            options: {
                dest: '<%= config.dist %>',
                flow: {
                    html: {
                        steps: {'js': ['concat'], 'css': ['concat', 'cssmin']},
                        post: {}
                    }
                }
            },
            html: '<%= config.app %>/index.html'
        },
```

I don't see this as a good solution, though - dependency management and build systems in JavaScript are complicated enough even without having to customize them specifically for individual libraries.

**Comment by glenpike** [comment]
:+1: Thanks @jzaefferer for this one, luckily it comes up in a bug search so I didn't have to spend ages looking for the problem.  Pity the owners "won't fix" this issue, but I can understand it's sort of someone elses mess.

**Comment by glenpike** [comment]
In addition to @byrichardpowell's comment, you can still mangle with uglify2 and the following config:

```
uglify2: {
    mangle: {
        except: ['$super']
    }
},
optimize: 'uglify2'
```

**Comment by agwidarsito** [comment]
I'll add to the growing list of people who have been bitten by this. Adding a note to the readme is a good start, although I feel this should be somewhere more visible too (if possible?)

Useful link: https://www.symphonious.net/2013/09/13/uglifyuglify2-rickshaw-requirejs-and-minification/

**Comment by gintsgints** [comment]
Solution for gulp:

```
.pipe($.uglify({ mangle: {except: '$super'} ,preserveComments: $.uglifySaveLicense })).on('error', conf.errorHandler('Uglify'))
```

**Comment by ceremcem** [comment]
For those who use gulp with `gulp-if-else` is as follows: 

```js
var myUglify;
myUglify = function(x){
  return uglify({
    mangle: {
      except: ['$super']
    }
  }, x);
};
```

Then replace `uglify` with `myUglify`: 

```js
        .pipe(ifElse(onlyCompile, myUglify))
```

**Comment by Conanza** [comment]
Running into this issue when using Rickshaw with Angular 5. When built for production, $super is being mangled. 

Angular-cli seems stiff and mostly unconfigurable. In most threads I've seen, Angular-cli team is not trying to support specifying of uglify options via cli or config.

**Comment by qcgm1978** [comment]
Meet a project built with wake and it works when ` "minify": false,` set.:)

**Comment by rei-ber** [comment]
for webpackv5 and terser I used this config:
```javascript
optimization: {
    minimizer: [new TerserPlugin({
        terserOptions: {
            mangle: {
                reserved: ['$super']
            }
        }
    })],
},
```
