### ISSUE TITLE
Request for minor release 

### ISSUE THREAD

**Issue by andriy-kudrya** [shutterstock/rickshaw#543]
It would be very useful to update d3 dependency for tag v1.5.1 to d3@3.5.17 and release updated npm package.

Latest version rickshaw@v1.5.1 uses d3 that depends on outdated jsdom that depends on contextify which has following problems:
- it requires Python 2 to be installed
- it requires unkown version of Visual Studio to be installed as well (with VS2012 installation fails)

This almost prevents to use rickshaw@v1.5.1 from npm (

**Comment by cesine** [comment]
1.6.0-rc.0  is out! https://www.npmjs.com/package/rickshaw

**Comment by cesine** [comment]
@andriy-kudrya v1.6.0 is out!
