### ISSUE TITLE
Images do not load for all examples 

### ISSUE THREAD

**Issue by RichardLitt** [shutterstock/rickshaw#573]
Some of the examples do not have images associated with them, and they do not load in the browser when you go to `examples/index.html`.

![screen shot 2017-07-14 at 1 31 06 pm](https://user-images.githubusercontent.com/910753/28223313-eed1c42c-6898-11e7-87af-e680ee2ff58a.png)

A list of the failed images:

- x_axis.png
- fixed.png
- formatter.png
- hover.png
- multi.png

As well, both header.js and footer.js fail to load. 

Mac OSX, recent clone, Chrome.

**Comment by cesine** [comment]
fixed in https://github.com/shutterstock/rickshaw/commit/daa62f4d313b58db2e95a6a9e6595db144776416
