### ISSUE TITLE
Add keywords from package.json to GitHub tags

### ISSUE THREAD

**Issue by RichardLitt** [shutterstock/rickshaw#582]
Hey there :wave:

You have some keywords in the `package.json` which are not labelled as tags in the GitHub metadata. These are: "d3",  "charts", "rickshaw", "svg", "graph". It would be great to add these tags to this repo.

**Comment by cesine** [comment]
@RichardLitt done!

<img width="754" alt="screen shot 2017-07-29 at 4 15 30 pm" src="https://user-images.githubusercontent.com/196199/28747954-450e6804-7479-11e7-8647-e4102726ca9f.png">
