### ISSUE TITLE
Using Rickshaw.Fixtures.formatBase1024KMGTP seems to cause Y axis to go weird

### ISSUE THREAD

**Issue by cmouse** [shutterstock/rickshaw#601]
With following configuration

```.js
var y_fixture = Rickshaw.Fixtures.Number.formatBase1024KMGPT;

var graph = new Rickshaw.Graph( {
    element: config.div.find(".chart")[0],
    width: 550,
    height: 250,
    renderer: config.renderer || 'multi',
    padding: { top: 0.05 },
    series: plotseries

});

var axes = new Rickshaw.Graph.Axis.Time( {
    graph: graph,
    orientation: 'bottom',
    timeFixture: new Rickshaw.Fixtures.Time.Local()
} );

var y_ticks = new Rickshaw.Graph.Axis.Y( {
    graph: graph,
    orientation: 'left',
    tickFormat: y_fixture,
    element: config.div.find(".y_axis")[0]
} );

var legend = new Rickshaw.Graph.Legend( {
    graph: graph,
    element: config.div.find(".legend")[0]
} );
```
I get following graph
![with-format1024kmgtp](https://user-images.githubusercontent.com/1204643/31337823-ae34fb30-ad05-11e7-9b4e-f94d40b61d43.png)

If I use `Rickshaw.Fixtures.Number.formatKMGT` I get the following one. (Which is same as KMBT but B changed to G).
![without-format1024kmgtp](https://user-images.githubusercontent.com/1204643/31337824-ae3a6bd8-ad05-11e7-9fda-f3b8041e4e8f.png)

**Comment by cmouse** [comment]
```.js
>Rickshaw.Fixtures.Number.formatBase1024KMGTP(11111111)
"10.596381187438965M"
>Rickshaw.Fixtures.Number.formatKMGT(11111111)
"11.111111M"
```

**Comment by cmouse** [comment]
The problem seems to be fixable by surrounding the divisions with `(y / factor).toFixed(2)`

**Comment by RichardLitt** [comment]
Interesting. Do you think the best option would be adding this information to documentation, or patching it?

**Comment by cmouse** [comment]
My feeling is that it should be patched, as it cannot be fixed without altering formatBase1024KMGTP function.
