### ISSUE TITLE
Question regarding minification

### ISSUE THREAD

**Issue by socketbox** [shutterstock/rickshaw#604]
I'm considering creating a PR and I wanted to know if a) I need to submit a minified version of the `rickshaw.js` file, and if so, b) which tool should I use to minify said file. I'm not aware of a global, GitHub standard and don't have enough experience with the JS community to know of one.

**Comment by RichardLitt** [comment]
You don't need to include one. We'll handle that. :)

**Comment by cesine** [comment]
@socketbox we have more info in the contributing doc, let us know if you have any other questions: https://github.com/shutterstock/rickshaw/blob/master/CONTRIBUTING.md#pull-requests-are-always-welcome
