### ISSUE TITLE
Different series length

### ISSUE THREAD

**Issue by javascriptlove** [shutterstock/rickshaw#63]
Any way to allow different series length to display "cut" areas. A typical usage would be to display 2 charts, the first one being displayed to current date, and the other one would "predict" the future chart flow (for financial charts etc.)

**Comment by rzachariah** [comment]
I am pumping realtime data into a rickshaw chart. The number of series I have grows over time. This works fine with a line chart. An area chart gives me this error:

`stacked series cannot have differing numbers of points: 3 vs 0; see Rickshaw.Series.fill()`

Is area with incomplete series a no go?
